export const ROOMS = [
  { id: "sales", name: "Sales Office", icon: "TrendingUp", agents: ["james-carter", "ethan-walker"] },
  { id: "research", name: "Lead Research Room", icon: "Search", agents: ["emma-collins"] },
  { id: "crm", name: "CRM Room", icon: "Database", agents: ["oliver-brooks"] },
  { id: "email", name: "Email Marketing Room", icon: "Mail", agents: ["sophia-bennett"] },
  { id: "success", name: "Customer Success Room", icon: "Heart", agents: ["isabella-morgan"] },
  { id: "partnerships", name: "Partnerships Room", icon: "Handshake", agents: ["victoria-green"] },
  { id: "market", name: "Market Intelligence Room", icon: "BarChart3", agents: ["liam-foster"] },
  { id: "social", name: "Social Media Room", icon: "Share2", agents: ["charlotte-hughes"] },
  { id: "product", name: "Product Room", icon: "Layers", agents: ["noah-richardson"] },
  { id: "boardroom", name: "Executive Boardroom", icon: "Users", agents: ["amelia-scott"] },
  { id: "ceo", name: "CEO Dashboard Room", icon: "Crown", agents: ["evelyn-stone"] },
] as const;

export const AGENTS = [
  {
    slug: "james-carter",
    name: "James Carter",
    role: "Senior Sales Development Representative",
    title: "SDR AI",
    room: "sales",
    bio: "Apollo, Clay, lead generation, prospecting trainers, breeders, consignors, owners, bloodstock agents, syndicates and stud farms.",
    tools: ["Apollo", "Clay", "HubSpot"],
    status: "RESEARCHING" as const,
    currentTask: "Finding UK and Ireland consignors for upcoming auctions",
    lastAction: "Found 24 new UK consignor leads from Apollo",
    avatarColor: "#8B1538",
  },
  {
    slug: "emma-collins",
    name: "Emma Collins",
    role: "Senior Market Intelligence Analyst",
    title: "Lead Research AI",
    room: "research",
    bio: "Researching leads, company profiles, auction participation, decision-makers and sales opportunities.",
    tools: ["Apollo", "Clay", "Perplexity"],
    status: "RESEARCHING" as const,
    currentTask: "Researching Highclere Thoroughbred Racing profile",
    lastAction: "Completed dossier on 12 Irish consignors",
    avatarColor: "#1E3A5F",
  },
  {
    slug: "oliver-brooks",
    name: "Oliver Brooks",
    role: "HubSpot CRM Manager",
    title: "CRM Manager AI",
    room: "crm",
    bio: "HubSpot contacts, companies, deals, notes, pipeline stages and CRM organization.",
    tools: ["HubSpot"],
    status: "UPDATING_CRM" as const,
    currentTask: "Updating pipeline with new consignor records",
    lastAction: "Updated HubSpot pipeline with 18 new contacts",
    avatarColor: "#FF7A59",
  },
  {
    slug: "sophia-bennett",
    name: "Sophia Bennett",
    role: "Personalized Outreach Specialist",
    title: "Email Marketing AI",
    room: "email",
    bio: "Email campaigns, follow-ups, newsletters and auction outreach drafts.",
    tools: ["Gmail", "HubSpot"],
    status: "WAITING_APPROVAL" as const,
    currentTask: "Drafting personalized emails for 12 consignor leads",
    lastAction: "Drafted 12 auction outreach emails pending approval",
    avatarColor: "#6B21A8",
  },
  {
    slug: "ethan-walker",
    name: "Ethan Walker",
    role: "Senior Sales Consultant",
    title: "Sales AI",
    room: "sales",
    bio: "Interested leads, sales calls, proposals, objections, plans and closing.",
    tools: ["HubSpot", "Gmail", "Google Calendar"],
    status: "IDLE" as const,
    currentTask: "Reviewing warm leads for follow-up",
    lastAction: "Flagged 3 warm leads for follow-up",
    avatarColor: "#0D9488",
  },
  {
    slug: "isabella-morgan",
    name: "Isabella Morgan",
    role: "Customer Success Manager",
    title: "Customer Success AI",
    room: "success",
    bio: "Onboarding, support, renewals and customer guidance.",
    tools: ["HubSpot", "Gmail"],
    status: "IDLE" as const,
    currentTask: "Monitoring onboarding queue",
    lastAction: "Sent renewal reminder to 2 accounts",
    avatarColor: "#DB2777",
  },
  {
    slug: "victoria-green",
    name: "Victoria Green",
    role: "Strategic Partnerships Manager",
    title: "Partnerships AI",
    room: "partnerships",
    bio: "Partnerships, investors, stud farms, auction houses, equine tech companies and universities.",
    tools: ["HubSpot", "Gmail"],
    status: "WRITING" as const,
    currentTask: "Drafting partnership proposal for Australian stud farm",
    lastAction: "Identified 5 partnership opportunities in AU/NZ",
    avatarColor: "#059669",
  },
  {
    slug: "liam-foster",
    name: "Liam Foster",
    role: "Thoroughbred Market Analyst",
    title: "Market Intelligence AI",
    room: "market",
    bio: "Monitoring Tattersalls, Goffs, Keeneland, Fasig-Tipton, OBS, Magic Millions, Inglis, NZB and JRHA.",
    tools: ["Perplexity", "Google Drive"],
    status: "RESEARCHING" as const,
    currentTask: "Compiling Tattersalls October Sale intelligence brief",
    lastAction: "Published weekly auction market digest",
    avatarColor: "#CA8A04",
  },
  {
    slug: "charlotte-hughes",
    name: "Charlotte Hughes",
    role: "Digital Marketing Manager",
    title: "Social Media AI",
    room: "social",
    bio: "Instagram, LinkedIn, Canva, content ideas, brand campaigns and social strategy.",
    tools: ["Canva", "LinkedIn", "Instagram"],
    status: "WRITING" as const,
    currentTask: "Creating LinkedIn campaign for auction season",
    lastAction: "Scheduled 4 posts for auction week",
    avatarColor: "#E11D48",
  },
  {
    slug: "noah-richardson",
    name: "Noah Richardson",
    role: "Product Strategy Manager",
    title: "Product Manager AI",
    room: "product",
    bio: "Roadmap, features, platform improvements, Lovable, Figma and GitHub coordination.",
    tools: ["Figma", "GitHub", "Lovable"],
    status: "IDLE" as const,
    currentTask: "Reviewing Q2 roadmap priorities",
    lastAction: "Updated feature spec for agent dashboard v2",
    avatarColor: "#4F46E5",
  },
  {
    slug: "amelia-scott",
    name: "Amelia Scott",
    role: "AI Operations Director",
    title: "Operations Manager AI",
    room: "boardroom",
    bio: "Coordinating all agents, assigning tasks and preventing duplicated work.",
    tools: ["Claude", "Internal API"],
    status: "COMPLETED" as const,
    currentTask: "Orchestrating UK/Ireland consignor workflow",
    lastAction: "Assigned tasks across 4 agents without duplication",
    avatarColor: "#374151",
  },
  {
    slug: "evelyn-stone",
    name: "Evelyn Stone",
    role: "Chief Executive Intelligence",
    title: "CEO Dashboard AI",
    room: "ceo",
    bio: "Executive reporting, daily summaries, pipeline, revenue, opportunities and recommended decisions.",
    tools: ["Claude", "HubSpot", "Internal API"],
    status: "WRITING" as const,
    currentTask: "Preparing daily CEO executive summary",
    lastAction: "Generated morning briefing with pipeline highlights",
    avatarColor: "#7F1D1D",
  },
] as const;

export type Agent = (typeof AGENTS)[number];

const agentBySlug = new Map<string, Agent>(AGENTS.map((agent) => [agent.slug, agent]));

export function getAgent(slug: string): Agent | undefined {
  return agentBySlug.get(slug);
}

export const officeRooms = ROOMS.map((room) => ({
  room,
  agents: AGENTS.filter((agent) => (room.agents as readonly string[]).includes(agent.slug)),
}));
