export const INTEGRATIONS = [
  { id: "claude", label: "Anthropic Claude", category: "AI", envKey: "ANTHROPIC_API_KEY" },
  { id: "openai", label: "OpenAI", category: "AI", envKey: "OPENAI_API_KEY" },
  { id: "perplexity", label: "Perplexity", category: "AI", envKey: "PERPLEXITY_API_KEY" },
  { id: "grok", label: "Grok (xAI)", category: "AI", envKey: "XAI_API_KEY" },
  { id: "tavily", label: "Tavily API", category: "Research", envKey: "TAVILY_API_KEY" },
  { id: "supabase", label: "Supabase", category: "Database", envKey: "SUPABASE_SERVICE_ROLE_KEY" },
  { id: "hubspot", label: "HubSpot", category: "CRM", envKey: "HUBSPOT_ACCESS_TOKEN" },
  { id: "salesforce", label: "Salesforce", category: "CRM", envKey: "SALESFORCE_ACCESS_TOKEN" },
  { id: "apollo", label: "Apollo.io", category: "Sales", envKey: "APOLLO_API_KEY" },
  { id: "clay", label: "Clay", category: "Sales", envKey: "CLAY_API_KEY" },
  { id: "n8n", label: "n8n Automation", category: "Automation", envKey: "N8N_AGENT_WEBHOOK_URL" },
  { id: "gmail", label: "Gmail", category: "Google Workspace", envKey: "GOOGLE_CLIENT_ID" },
  { id: "gcal", label: "Google Calendar", category: "Google Workspace", envKey: "GOOGLE_CLIENT_ID" },
  { id: "gdrive", label: "Google Drive", category: "Google Workspace", envKey: "GOOGLE_CLIENT_ID" },
  { id: "outlook", label: "Outlook", category: "Microsoft", envKey: "MICROSOFT_CLIENT_ID" },
  { id: "teams", label: "Microsoft Teams", category: "Microsoft", envKey: "MICROSOFT_CLIENT_ID" },
  { id: "meta", label: "Meta Business API", category: "Marketing", envKey: "META_ACCESS_TOKEN" },
  { id: "google-ads", label: "Google Ads", category: "Marketing", envKey: "GOOGLE_ADS_TOKEN" },
  { id: "linkedin", label: "LinkedIn", category: "Marketing", envKey: "LINKEDIN_ACCESS_TOKEN" },
] as const;
