export const AGENT_TEMPLATE_SEEDS = [
  {
    slug: "admin-ops",
    name: "Operations Administrator",
    department: "administrative",
    role: "Administrative Agent",
    description: "Manages email, calendar, documents, and meeting summaries.",
    capabilities: JSON.stringify([
      "Email management",
      "Calendar management",
      "Document organization",
      "Reports",
      "Meeting summaries",
    ]),
    integrations: JSON.stringify(["Gmail", "Google Calendar", "Google Drive"]),
    industryPack: null as string | null,
    avatarColor: "#6A0DAD",
  },
  {
    slug: "marketing-strategist",
    name: "Marketing Strategist",
    department: "marketing",
    role: "Marketing Agent",
    description: "Content, SEO, campaigns, and competitor research.",
    capabilities: JSON.stringify([
      "Content creation",
      "SEO",
      "Campaign planning",
      "Market analysis",
      "Competitor research",
    ]),
    integrations: JSON.stringify(["Google Ads", "LinkedIn"]),
    industryPack: null,
    avatarColor: "#7C3AED",
  },
  {
    slug: "social-manager",
    name: "Social Media Manager",
    department: "social",
    role: "Social Media Agent",
    description: "Content calendars and community management.",
    capabilities: JSON.stringify([
      "Content calendar",
      "Post generation",
      "Analytics",
      "Community management",
    ]),
    integrations: JSON.stringify(["Instagram", "Facebook", "LinkedIn", "TikTok"]),
    industryPack: null,
    avatarColor: "#E600A0",
  },
  {
    slug: "sales-hunter",
    name: "Sales Hunter",
    department: "sales",
    role: "Sales Agent",
    description: "Lead generation, qualification, and follow-up automation.",
    capabilities: JSON.stringify([
      "Lead generation",
      "Prospecting",
      "Lead qualification",
      "Follow-up automation",
    ]),
    integrations: JSON.stringify(["HubSpot", "Apollo.io", "Clay"]),
    industryPack: null,
    avatarColor: "#5B2A9E",
  },
  {
    slug: "finance-analyst",
    name: "Finance Analyst",
    department: "finance",
    role: "Finance Agent",
    description: "Reports, cash flow, forecasting, and expense monitoring.",
    capabilities: JSON.stringify([
      "Financial reports",
      "Cash flow analysis",
      "Forecasting",
      "Expense monitoring",
    ]),
    integrations: null,
    industryPack: null,
    avatarColor: "#4C1D95",
  },
  {
    slug: "research-intel",
    name: "Research Intelligence",
    department: "research",
    role: "Research Agent",
    description: "Market research and competitor intelligence.",
    capabilities: JSON.stringify([
      "Market research",
      "Competitor intelligence",
      "Industry reports",
    ]),
    integrations: JSON.stringify(["Perplexity", "Tavily"]),
    industryPack: null,
    avatarColor: "#B794F4",
  },
  {
    slug: "equine-lead-scout",
    name: "Equine Lead Scout",
    department: "sales",
    role: "Bloodstock Lead Agent",
    description: "Finds consignors and bloodstock leads (industry pack).",
    capabilities: JSON.stringify([
      "Lead generation",
      "Auction research",
      "Consignor outreach",
    ]),
    integrations: JSON.stringify(["Tavily", "HubSpot"]),
    industryPack: "Bloodstock / Equine",
    avatarColor: "#6A0DAD",
  },
];
