ALTER TABLE public.usage_tracking 
  ADD COLUMN IF NOT EXISTS action TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS credits_delta INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS balance_after INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS page_used TEXT DEFAULT '';