REVOKE ALL ON public.marketplace_listings FROM anon, authenticated;

GRANT SELECT (
  id,
  created_at,
  updated_at,
  horse_name,
  reference_code,
  date_of_birth,
  sex,
  breed,
  sire,
  dam,
  dam_sire,
  consignor_name,
  country,
  guide_price,
  offers_close_at,
  status,
  description_html,
  pedigree_json,
  report_pdf_url,
  video_url,
  photos,
  created_by,
  category,
  colour,
  cob,
  bonus_schemes,
  x_rays_available,
  scoping_video_available,
  repository_url,
  sire_notes_html,
  first_dam_notes_html,
  second_dam_notes_html,
  third_dam_notes_html,
  auction_sale_name,
  sale_stage
) ON public.marketplace_listings TO anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.marketplace_listings TO service_role;