// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-horses-for-sale.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
import { z } from "npm:zod@^3.25.76";
function client() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_horses_for_sale_default = defineTool({
  name: "list_horses_for_sale",
  title: "List horses for sale",
  description: "List horses currently available on the BloodstockAI marketplace. Optional filters by sex, status (active/sold), country code, and free-text search over horse name, sire, dam, and consignor.",
  inputSchema: {
    status: z.enum(["active", "sold", "all"]).optional().describe("Listing status filter. Default 'active'."),
    sex: z.string().optional().describe("Filter by sex (e.g. Colt, Filly, Mare)."),
    country: z.string().optional().describe("Filter by country name or ISO code."),
    search: z.string().optional().describe("Free-text search across horse name, sire, dam, consignor."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, sex, country, search, limit }) => {
    const sb = client();
    let q = sb.from("marketplace_listings_public").select("id,horse_name,reference_code,sex,date_of_birth,sire,dam,dam_sire,consignor_name,country,guide_price,status,offers_close_at,category").limit(limit ?? 20);
    if (status && status !== "all") q = q.eq("status", status);
    else q = q.in("status", ["active", "sold"]);
    if (sex) q = q.ilike("sex", sex);
    if (country) q = q.ilike("country", `%${country}%`);
    if (search) {
      const s = `%${search}%`;
      q = q.or(`horse_name.ilike.${s},sire.ilike.${s},dam.ilike.${s},consignor_name.ilike.${s},reference_code.ilike.${s}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { listings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-sales-catalogues.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.81.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_sales_catalogues_default = defineTool2({
  name: "list_sales_catalogues",
  title: "List sales catalogues",
  description: "List thoroughbred auction catalogues indexed by BloodstockAI (Tattersalls, Goffs, Arqana, Keeneland, Fasig-Tipton, Inglis, Magic Millions, OBS, etc.).",
  inputSchema: {
    auction_house: z2.string().optional().describe("Filter by auction house name (partial match)."),
    year: z2.number().int().optional().describe("Filter by sale year."),
    limit: z2.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ auction_house, year, limit }) => {
    const sb = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = sb.from("catalogues").select("id,auction_house,sale_name,sale_year,sale_date,total_lots,status,source_url").order("sale_date", { ascending: false }).limit(limit ?? 25);
    if (auction_house) q = q.ilike("auction_house", `%${auction_house}%`);
    if (year) q = q.eq("sale_year", year);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { catalogues: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-catalogue-lots.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.81.1";
import { z as z3 } from "npm:zod@^3.25.76";
var search_catalogue_lots_default = defineTool3({
  name: "search_catalogue_lots",
  title: "Search catalogue lots",
  description: "Search auction catalogue lots by horse name, sire, or dam. Returns pedigree summary, lot number, sale info, and BloodstockAI scores when available.",
  inputSchema: {
    query: z3.string().min(1).describe("Text to match against horse name, sire, or dam."),
    catalogue_id: z3.string().uuid().optional().describe("Optional: restrict to a specific catalogue id."),
    limit: z3.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, catalogue_id, limit }) => {
    const sb = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const s = `%${query}%`;
    let q = sb.from("catalogue_lots").select("id,catalogue_id,lot_number,horse_name,sex,year_born,sire,dam,dam_sire,consignor,sold_price,currency,overall_score,potential_score,lot_status").or(`horse_name.ilike.${s},sire.ilike.${s},dam.ilike.${s}`).limit(limit ?? 25);
    if (catalogue_id) q = q.eq("catalogue_id", catalogue_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lots: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "bloodstockai-mcp",
  title: "BloodstockAI",
  version: "0.1.0",
  instructions: "Tools for the BloodstockAI thoroughbred bloodstock platform. Use `list_horses_for_sale` for the private-sale marketplace, `list_sales_catalogues` to browse indexed auction sales (Tattersalls, Goffs, Arqana, Keeneland, etc.), and `search_catalogue_lots` to look up specific lots by horse, sire, or dam.",
  tools: [list_horses_for_sale_default, list_sales_catalogues_default, search_catalogue_lots_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
